import "src/styles/globals.css";
import Head from "next/head";
import Sidebar from "src/components/Sidebar/Sidebar";
import Feed from "src/components/Feed/Feed";
import Widgets from "src/components/Widgets/Widgets";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex h-screen max-w-7xl mx-auto py-0 px-3">
        <Sidebar />
        <Feed />
        <Widgets />
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
